name: 'Docs (devel)'
on:
  push:
    branches:
      - main


jobs:
  build:
    permissions:
      contents: write
    uses: './.github/workflows/docs.yml'
    with:
      git_commit: '${{ github.sha }}'
      git_devel: '${{ github.sha }}'
      gh_pages_dest_dir: './devel'
