name: 'Docs (release)'
on:
  release:
    types:
      - published


jobs:
  build:
    permissions:
      contents: write
    uses: './.github/workflows/docs.yml'
    with:
      git_commit: '${{ github.ref_name }}'
      git_devel: '${{ github.ref_name }}'
      gh_pages_dest_dir: './releases/${{ github.ref_name }}'
